#Author: Christian De La Torre and Ernesto Parra
#Class Account: cssc0786 and cssc0787
#Class: CS570, Summer 2019
#Assignment: Assignment #1, Thread Management
#Makefile

player:main.o
	g++ -std=c++11 main.o -o player -lpthread -lrt

main.o: main.cpp
	g++ -std=c++11 -c main.cpp